#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=1.8.6

before_install:
  - export DJANGO_SETTINGS_MODULE=settings.py
  - export PYTHONPATH=$HOME/build/seadsystem/website
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

script:
  - python manage.py collectstatic --noinput
  - python manage.py test

notifications:
  email: false